import * as express from 'express';
import router from './routes';
import * as cors from 'cors';
import * as fileUpload from 'express-fileupload';
const app = express();
app.use(express.json());
app.use(cors());
app.use(fileUpload());
app.use(router);
export default app;
